<?xml version="1.0" encoding="UTF-8"?>
<robot rpa="false" generated="20211026 19:40:53.110" schemaversion="2" generator="Robot 4.1.1 (Python 2.7.18 on linux2)">
<suite source="/home/abdulla/Desktop/Abdulla/JavaScript/projects/fullstack-renting-application/testing" id="s1" name="Testing">
<suite source="/home/abdulla/Desktop/Abdulla/JavaScript/projects/fullstack-renting-application/testing/Suites" id="s1-s1" name="Suites">
<suite source="/home/abdulla/Desktop/Abdulla/JavaScript/projects/fullstack-renting-application/testing/Suites/Main-Suite.robot" id="s1-s1-s1" name="Main-Suite">
<test id="s1-s1-s1-t1" name="t2">
<kw name="Log" library="BuiltIn">
<arg>Hell</arg>
<doc>Logs the given message with the given level.</doc>
<msg timestamp="20211026 19:40:53.138" level="INFO">Hell</msg>
<status status="PASS" endtime="20211026 19:40:53.138" starttime="20211026 19:40:53.138"/>
</kw>
<status status="PASS" endtime="20211026 19:40:53.138" starttime="20211026 19:40:53.137"/>
</test>
<status status="PASS" endtime="20211026 19:40:53.138" starttime="20211026 19:40:53.135"/>
</suite>
<status status="PASS" endtime="20211026 19:40:53.139" starttime="20211026 19:40:53.134"/>
</suite>
<status status="PASS" endtime="20211026 19:40:53.140" starttime="20211026 19:40:53.116"/>
</suite>
<statistics>
<total>
<stat fail="0" skip="0" pass="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="0" skip="0" id="s1" name="Testing" pass="1">Testing</stat>
<stat fail="0" skip="0" id="s1-s1" name="Suites" pass="1">Testing.Suites</stat>
<stat fail="0" skip="0" id="s1-s1-s1" name="Main-Suite" pass="1">Testing.Suites.Main-Suite</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20211026 19:40:53.114" level="ERROR">Taking listener '/home/abdulla/.local/lib/python3.8/site-packages/robotide/contrib/testrunner/TestRunnerAgent.py:41533:False' into use failed: Importing listener '/home/abdulla/.local/lib/python3.8/site-packages/robotide/contrib/testrunner/TestRunnerAgent.py' failed: ImportError: No module named socketserver
Traceback (most recent call last):
  File "/home/abdulla/.local/lib/python3.8/site-packages/robotide/contrib/testrunner/TestRunnerAgent.py", line 81, in &lt;module&gt;
    raise e
PYTHONPATH:
  /home/abdulla/.local/bin
  /usr/lib/python2.7
  /usr/lib/python2.7/plat-x86_64-linux-gnu
  /usr/lib/python2.7/lib-tk
  /usr/lib/python2.7/lib-old
  /usr/lib/python2.7/lib-dynload
  /home/abdulla/.local/lib/python2.7/site-packages
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages</msg>
</errors>
</robot>
